Adding the One sample t-test for Python
PSIAIMS/CAMIS pull request #186
Opened 2024-04-15 13:05 UTC by LukasBrausch

This PR aims to introduce the One sample t-test for Python.

2024-04-16 15:18 UTC, statasaurus requested changes
This looks really good @LukasBrausch,  I just have some minor formatting requests. But, it looks like you were able to get the requirements updated so that is great to see

2024-04-16 15:18 UTC, statasaurus commented on python/OneSampleTTest.qmd
> +---
The part outside of the code blocks just follow traditional markdown notation so like the following 
```suggestion
## One Sample t-test in Python
```

2024-04-16 15:18 UTC, statasaurus commented on python/OneSampleTTest.qmd
> +---
See above 
```suggestion
## Data Used

```

2024-04-17 07:35 UTC, LukasBrausch commented
Thank you very much for the suggestions, @statasaurus. I accepted them just now. Once I get a feeling for how things work around here, I hope to be able to commit some further Python comparisons. :)

Have a great day.

2024-04-17 08:38 UTC, statasaurus approved these changes
This looks great thank you!

2024-04-17 08:39 UTC, merged