Update PCA_analysis.qmd and added 3d plots
PSIAIMS/CAMIS pull request #254
Opened 2024-08-01 17:05 UTC by samrit2442

Added 3d visualisation of PCA

2024-08-02 12:23 UTC, statasaurus requested changes
Just a minor change but it looks good

2024-08-02 12:23 UTC, statasaurus commented on R/PCA_analysis.qmd
> +library(plotly)
```suggestion

```
You are calling plotly twice in the script it is unnecessary

2024-08-02 15:02 UTC, samrit2442 commented
Yes. I approved the changes.

2024-08-02 17:41 UTC, samrit2442 reviewed
Made the changes.

2024-08-05 10:39 UTC, statasaurus approved these changes
Looks great!

2024-08-05 10:40 UTC, merged