Friedman test - Comp
PSIAIMS/CAMIS pull request #287
Opened 2024-08-21 07:18 UTC by feng-4chen

Added R vs SAS code for Friedman test which is a nonparametric test for one-way repeated measures ANOVA on a simulated dataset. The code for the simulated data is also included.

2024-08-21 16:50 UTC, orladoylenvs requested changes
Thanks for the submission. 

There are already R and SAS implementations for Friedman's - would you like to combine yours?
R version is here: https://github.com/PSIAIMS/CAMIS/blob/main/R/R_Friedmantest.qmd
SAS version is here: 
https://github.com/PSIAIMS/CAMIS/blob/main/SAS/SAS_Friedmantest.qmd

We don't have a SAS vs. R so that's a nice addition! Thank you!

2024-08-21 16:50 UTC, orladoylenvs commented on R/friedman.qmd
> +#| eval: false
eval should be true to ensure you have imported tidyverse

2024-08-21 16:50 UTC, orladoylenvs commented on R/friedman.qmd
> +## title: "friedman's test"
In a quarto file the the page should begin with the following format with just three dashes to denote the beginning and end:
# ---
# title: "Friedman's Test"
# ---

2024-08-21 16:50 UTC, orladoylenvs commented on Comp/r-sas_friedman.qmd
> +------------------------------------------------------------------------
In a quarto file the the page should begin with the following format with just three dashes to denote the beginning and end:

2024-08-22 16:47 UTC, orladoylenvs commented
Hi @feng-4chen  I think we still need to address the duplicates for Friedman in SAS and R? How would you like to proceed?

2024-08-23 02:23 UTC, feng-4chen commented
> Hi @feng-4chen I think we still need to address the duplicates for Friedman in SAS and R? How would you like to proceed?

I worked with Sarfaraz together on Friedman. Maybe I could merge my SAS vs R compare in R file

2024-08-25 13:16 UTC, orladoylenvs commented
Hi @feng-4chen, I'm not sure I am following. Apologies if I am repeating myself... 

For R: 
You contributed R/friendman.qmd and Safaraz contributed R/R_Friedmantest.qmd - these need to be merged into one file. For e.g. adding yours as an extra example. 

For SAS:
You contributed SAS/friedman.qmd and Safaraz contributed SAS/SAS_Friedmantest.qmd - these need to be merged into one file.  For e.g. adding yours as an extra example. 

For SAS vs R: 
You contributed Comp/r-sas_friedman.qmd and this is the only SAS vs R comparison so this is great and no action is needed.

2024-08-26 01:37 UTC, feng-4chen commented
> Hi @feng-4chen, I'm not sure I am following. Apologies if I am repeating myself...
> 
> For R: You contributed R/friendman.qmd and Safaraz contributed R/R_Friedmantest.qmd - these need to be merged into one file. For e.g. adding yours as an extra example.
> 
> For SAS: You contributed SAS/friedman.qmd and Safaraz contributed SAS/SAS_Friedmantest.qmd - these need to be merged into one file. For e.g. adding yours as an extra example.
> 
> For SAS vs R: You contributed Comp/r-sas_friedman.qmd and this is the only SAS vs R comparison so this is great and no action is needed.
I will just keep Comp/r-sas_friedman.qmd. The other two is similar content with Safaraz so it' ok. Thanks for explaining!

2024-08-26 06:55 UTC, feng-4chen commented
Duplicate SAS/friedman.pmd and R/friedman.qmd removed from branch

2024-08-30 09:46 UTC, merged