update rounding parts for SAS, R and SAS vs R
PSIAIMS/CAMIS pull request #316
Opened 2024-09-20 03:02 UTC by pangchaoran

Add more details in R/rounding.qmd, SAS/rounding.qmd, Comp/r-sas_rounding.qmd

2024-09-20 14:30 UTC, statasaurus requested changes
For the R code can you make it run rather than using eval=FALSE?

2024-09-25 15:57 UTC, orladoylenvs commented on R/rounding.qmd
> +```{R, eval=FALSE}
To action Christina's comment you can try the suggestion below, eval=True is the default

```suggestion
```{r}
```

2024-10-08 15:59 UTC, statasaurus approved these changes
I have just added the updates it is great thank you

2024-10-08 15:59 UTC, merged

2024-10-12 06:13 UTC, pangchaoran commented
> I have just added the updates it is great thank you

Sorry for the late reply. And thanks for the update.