initial version
PSIAIMS/CAMIS pull request #78
Opened 2023-04-27 13:36 UTC by vjainwg

2023-05-11 13:20 UTC, DrLynTaylor requested changes

2023-05-11 13:20 UTC, DrLynTaylor commented on SAS/ttest.qmd
> +Note: Before entering straight into the t-test we need to check whether the assumptions (like the equality of variance, the observations should be independent, observations should be normally distrib
Please change "we need to go with the non-parametric test of independent t test."   
to:  "we may consider using a suitable non-parametric test."

2023-05-11 13:20 UTC, DrLynTaylor commented on SAS/ttest.qmd
> +1.  Normality: We have checked the normality of the observations using the code below. Here for both the treatment groups we have P value greater than 0.05 (Shapiro-Wilk test is used), therefore the
Please change:  "1. Normality: We have checked"  to be:
"1. Normality: You can check for data to be normally distributed by plotting a histogram of the data by treatment. Alternatively, you can use the Shapiro-Wilk test or the Kolmogorov-Smirnov test.  If the test is <0.05 and your sample is quite small then this suggests you should not use the t-test. However, if your sample in each treatment group is large (say >30 in each group), then you do not need to rely so heavily on the assumption that the data have an underlying normal distribution in order to apply the two-sample t-test.  This is where plotting the data using histograms can help to support investigation into the normality assumption.  We have checked"......

2023-05-11 13:20 UTC, DrLynTaylor commented on SAS/ttest.qmd
> +
Suggest to add after "we will consider the pooled method for t test".
If the F test is statistically significant (p<0.05), then the pooled t-test may give erroneous results.  In this instance, if it is believed that the population variances may truly differ, then the Satterthwaite (unequal variances) analysis results should be used.  These are provided in the SAS output alongside the Pooled results as default.

2023-06-08 13:03 UTC, statasaurus approved these changes

2023-06-08 13:04 UTC, merged